### ISSUE TITLE
TrungOre - Amount of emissionTokens are stucked in the vault due to rounding calculation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#89]
TrungOre

medium

# Amount of emissionTokens are stucked in the vault due to rounding calculation

## Summary
Using round-down to calculate amount of distributing emissionTokens make some emissionTokens stuck in the contract
 
## Vulnerability Detail
Implementation. of function `Carousel.previewEmissionWithdraw()` is as follows: 
```solidity=
function previewEmissionsWithdraw(uint256 _id, uint256 _assets)
    public
    view
    returns (uint256 entitledAmount)
{
    entitledAmount = _assets.mulDivDown(emissions[_id], finalTVL[_id]);
}
```
It was used in function `Carousel.withdraw()` to calculate the emissions to withdraw. Assume that `_assets * emissions[_id]` isn't divisible by `finalTVL`, an amount of emissionTokens won't be transfered to users. 
For instance, 
* `_asset = 9`, `emissions[_id] = 15`, `finalTVL = 10`
--> `entitleAmount = 9 * 15 / 10 = 13.5 > 13`

The amount of emissionTokens is freezed in vault contract can reach to nearly`finalTVL` for each epoch. 
Note that this issue also happens for function `VaultV2.previewWithdraw()`.

## Impact
Amount of emissionTokens are freezed in the vault contracts. 

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L630-L636

## Tool used
Manual review 

## Recommendation
Create a new function to let the owner withdraw the remaining amount of emissionToken out of vault

**Comment by 3xHarry** [comment]
considering this, however, mulDivDown was chosen on purpose, to prevent revert by underflow. It's more important that the withdraw function is not reverting instead of leaving some dust, especially bc its used in the while loops.

**Comment by pauliax** [comment]
Escalate for 10 USDC.

I think this should be low/informational. There is no significant loss, watson's provided example is not representative because in most cases tokens have decimals to reduce the significance of the precision loss. You can't escape floating point precision problems when performing multiplication/division operations. This should not leak much value and a function to rescue remaining tokens is nice to have but not mandatory.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> I think this should be low/informational. There is no significant loss, watson's provided example is not representative because in most cases tokens have decimals to reduce the significance of the precision loss. You can't escape floating point precision problems when performing multiplication/division operations. This should not leak much value and a function to rescue remaining tokens is nice to have but not mandatory.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by VAD37** [comment]
Escalate for 11 USDC

I am pretty sure the rounding loss/gain would be exact 1 wei for each user. Which is insignificant.

There are also 3 other issues explain the same thing but excluded. These should be awarded too if this is medium issue.

#025 rounding User will receive a smaller amount of tokens than the actual amount because of rounding down in the previewEmissionsWithdraw and previewWithdraw

#314 rounding Math rounding in VaultV2.sol is not ERC4626-complicant: previewWithdraw should round up.

#312  rounding User can burn shares and receive no assets in return

Also, if author change to mulDivUp(), there is a good chance that the last user withdraw will be reverted, which turn this into another high issue. Because there was no mulDivDown() in deposit function (intentional I guess).

Use mulDivDown() here instead of mulDivUp() pretty reasonable since this is not ERC4626 holding only 1 asset. The vault contract act like ERC1155 holding multi token over multiple epoch.

The code author seemed quite lazy to write balanceOf() function to keep track of the whole epoch thing. And just let ControllerPeggedAssetV2 just paste totalSupply() value directly into VaultV2. Just so, Vault can calculate share balance for each user based on final totalSupply() instead of current balanceOf() like ERC4626 standard.

This seem like a fast approach as it cut down devlopment time. Otherwise code author would have use mulDivUp() like actual ERC4626 solmate implementation.

**Comment by sherlock-admin** [comment]
> Escalate for 11 USDC
> 
> I am pretty sure the rounding loss/gain would be exact 1 wei for each user. Which is insignificant.
> 
> There are also 3 other issues explain the same thing but excluded. These should be awarded too if this is medium issue.
> 
> #025 rounding User will receive a smaller amount of tokens than the actual amount because of rounding down in the previewEmissionsWithdraw and previewWithdraw
> 
> #314 rounding Math rounding in VaultV2.sol is not ERC4626-complicant: previewWithdraw should round up.
> 
> #312  rounding User can burn shares and receive no assets in return
> 
> Also, if author change to mulDivUp(), there is a good chance that the last user withdraw will be reverted, which turn this into another high issue. Because there was no mulDivDown() in deposit function (intentional I guess).
> 
> Use mulDivDown() here instead of mulDivUp() pretty reasonable since this is not ERC4626 holding only 1 asset. The vault contract act like ERC1155 holding multi token over multiple epoch.
> 
> The code author seemed quite lazy to write balanceOf() function to keep track of the whole epoch thing. And just let ControllerPeggedAssetV2 just paste totalSupply() value directly into VaultV2. Just so, Vault can calculate share balance for each user based on final totalSupply() instead of current balanceOf() like ERC4626 standard.
> 
> This seem like a fast approach as it cut down devlopment time. Otherwise code author would have use mulDivUp() like actual ERC4626 solmate implementation.

You've created an escalation for 11 USDC, however, the escalation amount is fixed at 10 USDC.
To update the escalation with the correct amount, please edit this comment. **(do not create a new comment)**

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by dmitriia** [comment]
Agree on low. Re rounding list, not all issues that involve it are dups. Rounding per se is usual and oftentimes viable part of the logic of an arbitrary Vault.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low. 
Considering this issue as low based on the above escalations.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low. 
> Considering this issue as low based on the above escalations. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
